const requestData = [
  {
    user_id: "1",
    fname: "John",
    lname: "Doe",
    username: "@johndoe",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    user_id: "2",
    fname: "Jane",
    lname: "Smith",
    username: "@janesmith",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    user_id: "3",
    fname: "Alice",
    lname: "Johnson",
    username: "@alicejohnson",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    user_id: "4",
    fname: "Bob",
    lname: "Brown",
    username: "@bobbrown",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    user_id: "5",
    fname: "John",
    lname: "Doe",
    username: "@johndoe",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    user_id: "6",
    fname: "Jane",
    lname: "Smith",
    username: "@janesmith",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    user_id: "7",
    fname: "Alice",
    lname: "Johnson",
    username: "@alicejohnson",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    user_id: "8",
    fname: "Bob",
    lname: "Brown",
    username: "@bobbrown",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    user_id: "9",
    fname: "John",
    lname: "Doe",
    username: "@johndoe",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    user_id: "10",
    fname: "Jane",
    lname: "Smith",
    username: "@janesmith",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    user_id: "11",
    fname: "Alice",
    lname: "Johnson",
    username: "@alicejohnson",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    user_id: "12",
    fname: "Bob",
    lname: "Brown",
    username: "@bobbrown",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    user_id: "13",
    fname: "John",
    lname: "Doe",
    username: "@johndoe",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    user_id: "14",
    fname: "Jane",
    lname: "Smith",
    username: "@janesmith",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    user_id: "15",
    fname: "Alice",
    lname: "Johnson",
    username: "@alicejohnson",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    user_id: "16",
    fname: "Bob",
    lname: "Brown",
    username: "@bobbrown",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    user_id: "17",
    fname: "John",
    lname: "Doe",
    username: "@johndoe",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    user_id: "18",
    fname: "Jane",
    lname: "Smith",
    username: "@janesmith",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    user_id: "19",
    fname: "Alice",
    lname: "Johnson",
    username: "@alicejohnson",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    user_id: "20",
    fname: "Bob",
    lname: "Brown",
    username: "@bobbrown",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    user_id: "21",
    fname: "John",
    lname: "Doe",
    username: "@johndoe",
    profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    user_id: "22",
    fname: "Jane",
    lname: "Smith",
    username: "@janesmith",
    profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    user_id: "23",
    fname: "Alice",
    lname: "Johnson",
    username: "@alicejohnson",
    profileImage: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    user_id: "24",
    fname: "Bob",
    lname: "Brown",
    username: "@bobbrown",
    profileImage: "https://randomuser.me/api/portraits/men/4.jpg",
  },
];

export default requestData;
